name: Lab 05

on:
  push:
    branches:
      - main
      - lab05
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm generate

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: 2048-app-build
          path: .output/public/
          retention-days: 1
  preview:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/lab05' && github.event_name == 'pull_request'
    environment:
      name: preview

    steps:
      - uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v6
        with:
          name: 2048-app-build
          path: .output
      - name: Deploy to Vercel
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --confirm
  production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/lab05'
    environment:
      name: production

    steps:
      - uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v6
        with:
          name: 2048-app-build
          path: .output
      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm