name: CI Yasmine

env:
    NODE_VERSION :22 

on:
  push:
    branches: [ lab4 ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ lab4 ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
    inputs:
      launchStatiticAnalyse:
        description: 'Whether to launch static analysis (lint and typecheck) or not'
        required: false
        type: boolean
        default: 'true'
        environment:
          description: ''
          required: false
          type: choise
          options :
              -dev
              -prod
              -QA
              -UAT
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload build artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v6
        with:
          name: 2048-app-build
          path: .output/
          retention-days: ${{ github.ref == 'refs/heads/main' && 7 || 1 }}


  lint:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Type checking
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: deploy to environment
        run: echo "Deployeing to $ENVIRONMENT"
        ENV:
          ENVIRONMENT :${{inputs.environment}}