name: Run Lab 2 Script

on:
  push:
    branches:
      - lab3
  workflow_dispatch:

jobs:
  lab2-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Lab 2 script
        run: bash deliverables/lab02/lab2.sh
